### ISSUE TITLE
Fails with unix display

### ISSUE THREAD

**Issue by yurivict** [python-xlib/python-xlib#121]
This testcase
```
from Xlib.display import Display
display = Display()
```
fails when DISPLAY=unix:0.0
```
Traceback (most recent call last):
  File "testcase-xlib-problem.py", line 4, in <module>
    display = Display()
  File "/usr/local/lib/python2.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python2.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python2.7/site-packages/Xlib/protocol/display.py", line 93, in __init__
    name, host, displayno)
  File "/usr/local/lib/python2.7/site-packages/Xlib/support/connect.py", line 102, in get_auth
    return mod.get_auth(sock, dname, host, dno)
  File "/usr/local/lib/python2.7/site-packages/Xlib/support/unix_connect.py", line 133, in new_get_auth
    addr = bytearray(int(x) for x in octets)
  File "/usr/local/lib/python2.7/site-packages/Xlib/support/unix_connect.py", line 133, in <genexpr>
    addr = bytearray(int(x) for x in octets)
ValueError: invalid literal for int() with base 10: '/'
```

Found on FreeBSD 11.1

**Comment by yurivict** [comment]
It works with master, thanks!
Please consider making a release.
