### ISSUE TITLE
BrokenPipeError not correctly handled

### ISSUE THREAD

**Issue by oneindelijk** [python-xlib/python-xlib#127]
I get this error when using pynput (it completely crashes my X)

`Exception in thread Thread-4481:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/display.py", line 584, in send_and_recv
    i = self.socket.send(self.data_send)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/site-packages/pynput/_util/__init__.py", line 136, in run
    self._run()
  File "/usr/lib/python3.7/site-packages/pynput/keyboard/_xorg.py", line 499, in _run
    super(Listener, self)._run()
  File "/usr/lib/python3.7/site-packages/pynput/_util/xorg.py", line 401, in _run
    self._suppress_stop(dm)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/lib/python3.7/site-packages/pynput/_util/xorg.py", line 74, in display_manager
    display.sync()
  File "/usr/lib/python3.7/site-packages/Xlib/display.py", line 182, in sync
    self.get_pointer_control()
  File "/usr/lib/python3.7/site-packages/Xlib/display.py", line 833, in get_pointer_control
    return request.GetPointerControl(display = self.display)
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/rq.py", line 1381, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/display.py", line 586, in send_and_recv
    self.close_internal('server: %s' % err[1])
TypeError: 'BrokenPipeError' object is not subscriptable`

So the exception mightbe something from pynput or that I'm doing wrong,
but the exception following the exception seems to be in 
/usr/lib/python3.7/site-packages/Xlib/protocol/display.py", line 586

**Comment by oneindelijk** [comment]
This only seem to happen when adding the paramater `suppress=True` to the Listener

**Comment by vasily-v-ryabov** [comment]
@oneindelijk if it's still actual, please check if release 0.27 fixes this issue.

**Comment by frederik-uni** [comment]
still happens.

The issue is most likely if the display doenst exist anymore(stopped and started again)
```
bot-1-1  | Traceback (most recent call last):
bot-1-1  |   File "/usr/local/lib/python3.12/site-packages/Xlib/protocol/display.py", line 583, in send_and_recv
bot-1-1  |     i = self.socket.send(self.data_send)
bot-1-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot-1-1  | BrokenPipeError: [Errno 32] Broken pipe
bot-1-1  | 
bot-1-1  | During handling of the above exception, another exception occurred:
bot-1-1  | 
bot-1-1  | Traceback (most recent call last):
bot-1-1  |   File "/usr/local/lib/python3.12/site-packages/Xlib/xobject/drawable.py", line 594, in query_pointer
bot-1-1  |     return request.QueryPointer(display = self.display,
bot-1-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot-1-1  |   File "/usr/local/lib/python3.12/site-packages/Xlib/protocol/rq.py", line 1368, in __init__
bot-1-1  |     self.reply()
bot-1-1  |   File "/usr/local/lib/python3.12/site-packages/Xlib/protocol/rq.py", line 1380, in reply
bot-1-1  |     self._display.send_and_recv(request = self._serial)
bot-1-1  |   File "/usr/local/lib/python3.12/site-packages/Xlib/protocol/display.py", line 586, in send_and_recv
bot-1-1  |     raise self.socket_error
bot-1-1  | Xlib.error.ConnectionClosedError: Display connection closed by server: [Errno 32] Broken pipe
```
