### ISSUE TITLE
Bad display name, macOS

### ISSUE THREAD

**Issue by alexwms** [python-xlib/python-xlib#149]
Hello,
I am running macOS Mojave and I am trying to use python-xlib. I am using version 0.25 of python-xlib. 

Here is the traceback that I am getting:

python3 main.py
{'style': PosixPath('/Users/alex/.config/inkscape-shortcut-manager/styles'), 'object': PosixPath('/Users/alex/.config/inkscape-shortcut-manager/objects')}
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    main()
  File "main.py", line 78, in main
    disp = Display()
  File "/usr/local/lib/python3.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.7/site-packages/Xlib/protocol/display.py", line 84, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/usr/local/lib/python3.7/site-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/usr/local/lib/python3.7/site-packages/Xlib/support/unix_connect.py", line 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name "/private/tmp/com.apple.launchd.kzHzmjnNw7/org.macosforge.xquartz:0"

It seems that the regex match that is being performed on the string ``"/private/tmp/com.apple.launchd.kzHzmjnNw7/org.macosforge.xquartz:0"`` is failing, but I have no idea what is wrong (I have no programming experience with python-xlib/xquartz). I would be grateful if someone could help me out!

Best,
Alex

**Comment by sleepymalc** [comment]
I'm configuring [this repo](https://github.com/gillescastel/inkscape-shortcut-manager) also recently on macOS, and I can't figure out how to deal with this issue also. I think the first thing first is to add an `$DISPLAY` environment variable first since there seems no default one. But then I get the further error:
`{'style': PosixPath('/Users/pbb/.config/inkscape-shortcut-manager/styles'), 'object': PosixPath('/Users/pbb/.config/inkscape-shortcut-manager/objects')}
Traceback (most recent call last):
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 119, in get_socket
    s = _get_unix_socket(address)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 98, in _get_unix_socket
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 123, in get_socket
    s = _get_tcp_socket(host, dno)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 93, in _get_tcp_socket
    s.connect((host, 6000 + dno))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 79, in main
    disp = Display()
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 127, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":0.0": [Errno 61] Connection refused
`

**Comment by vasily-v-ryabov** [comment]
Did you try `xeyes` utility? Is X11 forwarding enabled by `ssh -X`?

**Comment by dawid-laszuk-sp** [comment]
For anyone facing, this might not be achievable(?)

https://stackoverflow.com/questions/63254722/python-key-logger-error-displaynameerror-bad-display-name

**Comment by MestreLion** [comment]
I wonder why was this labeled as a bug? macOS does not use `X`/`X11` at all, it uses a completely different display server called [Quartz Compositor](https://en.wikipedia.org/wiki/Quartz_Compositor), so it is expected that this library does work there at all. 

if `XQuartz` is some sort of macOS compatibility layer so Quartz can "emulate" X for clients, then it should set `$DISPLAY` by itself... in Linux it is set to `:0` (not `:0.0`). Check XQuartz documentation on what is its default display name.

**Comment by vasily-v-ryabov** [comment]
@MestreLion XQuartz should be installed additionally: https://www.xquartz.org/ BTW, absence of it may be the root cause for the whole thread. :) I personally didn't check it on my side. It's just a wild guess.

**Comment by MestreLion** [comment]
@vasily-v-ryabov , I believe the `bug` label is misleading, as this is not a bug in `python-xlib`: it requires a functional `X` environment, be it a real X11 server or emulated by XQuartz.

Also, this issue can be closed, or changed to a `Documentation` issue to add some information in `README` to tell macOS about the XQuartz requirement, and possibly some help setting it up for `python-xlib`.

**Comment by petli** [comment]
@MestreLion The original poster said they're using XQuartz, and the display name in the exception also mentions that. I think the issue is just that python-xlib must be able to recognise these display names and know how to open them (I guess they are Unix sockets, but I'm not sure what the `:0` at the end means).
