### ISSUE TITLE
Sending a pointer button press/release event

### ISSUE THREAD

**Issue by matanster** [python-xlib/python-xlib#177]
Sometimes it is hard to guess what arguments to provide when building an event. It may look like unlike the original C Xlib where everything is documented, there is no explicit documentation for constructing this event. Here's some code attempt and the error received for it.

```python
import time

from Xlib.display import Display
from Xlib import XK, protocol, X

display = Display()
screen = display.screen()

pointer_data = display.screen().root.query_pointer()

# get the active window (actually, active can be more complicated, e.g. http://python-xlib.sourceforge.net/doc/html/python-xlib_14.html)
window = display.get_input_focus().focus

event_details = dict(
    root=screen.root,
    window=window,
    same_screen=0, child=X.NONE,
    root_x=pointer_data.root_x, root_y=pointer_data.root_y,
    event_x=pointer_data.win_x, event_y=pointer_data.win_y,
    state=0,  # or e.g. Xlib.X.ShiftMask
    detail=1
)

# Key down event
event = protocol.event.ButtonPress(
            dict(event_details,
                 time=int(time.time())))

window.send_event(event, propagate=True)

event = protocol.event.ButtonRelease(
            dict(event_details,
                 time=int(time.time())))

window.send_event(event, propagate=True)

# flush the event pair
display.flush()
```

And the traceback:

> Traceback (most recent call last):
    event = protocol.event.ButtonPress(
  File "/home/matan/anaconda3/envs/nui/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1411, in __init__
    self._data, data = self._fields.parse_binary(binarydata, display,
  File "/home/matan/anaconda3/envs/nui/lib/python3.8/site-packages/Xlib/protocol/rq.py", line 1155, in parse_binary
    val = struct.unpack(self.static_codes, data[:self.static_size])
TypeError: unhashable type: 'slice'

Your comments would be much appreciated.

**Comment by matanster** [comment]
Opened in error
