### ISSUE TITLE
Xlib.error.DisplayConnectionError: Can't connect to display ":1": [Errno 111] Connection refused

### ISSUE THREAD

**Issue by aligokkaya** [python-xlib/python-xlib#190]
```
Traceback (most recent call last):
  File "wp.py", line 1, in <module>
    import pywhatkit
  File "/usr/local/lib/python3.8/dist-packages/pywhatkit/__init__.py", line 4, in <module>
    from pywhatkit.mainfunctions import sendwhatmsg_to_group, watch_tutorial_in_English, watch_tutorial_in_Hindi, developer_contact, showHistory, shutdown, cancelShutdown, prnt_sleeptm, check_window, sendwhatmsg, info, playonyt, image_to_ascii_art, search
  File "/usr/local/lib/python3.8/dist-packages/pywhatkit/mainfunctions.py", line 3, in <module>
    import pyautogui as pg
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 241, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.8/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":1": b'No protocol specified\n'
```

**Comment by vasily-v-ryabov** [comment]
Looks like a problem with xauth. Similar problem was solved here: https://unix.stackexchange.com/a/118826/191102
