### ISSUE TITLE
Connecting to the display doesn't work with xhost

### ISSUE THREAD

**Issue by TestingPlant** [python-xlib/python-xlib#198]
On Arch Linux, when using the `xhost` command to allow a user to access another user's X server, creating a display fails.
I'm using python-xlib 0.30 and xhost 1.0.8.

A small example is:
```py
from Xlib.display import Display
display = Display()
```
which errors with
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 119, in get_socket
    s = _get_unix_socket(address)
  File "/usr/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 98, in _get_unix_socket
    s.connect(address)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 123, in get_socket
    s = _get_tcp_socket(host, dno)
  File "/usr/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 93, in _get_tcp_socket
    s.connect((host, 6000 + dno))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/code.py", line 2, in <module>
    display = Display()
  File "/usr/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
  File "/usr/lib/python3.9/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
  File "/usr/lib/python3.9/site-packages/Xlib/support/unix_connect.py", line 127, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":0": [Errno 111] Connection refused
```
`/tmp/code.py` is the example above
Other programs like `glxgears` and `xeyes` run fine. When running on the original user account with a graphical session, this runs fine too.
I used
```bash
xhost +SI:localuser:foo
sudo -u foo bash
python3 /path/to/file.py
```
to run the above file, where `foo` is another user account.

**Comment by TestingPlant** [comment]
As a temporary solution, using
```bash
chown user0:user1 /tmp/.X11-unix/X0
chmod g+rwx /tmp/.X11-unix/X0
```
worked for me, where `user0` is the user with the graphical session and `user1` is the user without one (the one I'm logging into with `sudo`)
