### ISSUE TITLE
Display name error& Further issues

### ISSUE THREAD

**Issue by sleepymalc** [python-xlib/python-xlib#208]
I'm configuring [this repo](https://github.com/gillescastel/inkscape-shortcut-manager) recently on macOS, and I can't figure out how to deal with the same issue with #149  also. I think the first thing first is to add an `$DISPLAY` environment variable(I use `:0.0`, I thought this is kind of a default one, but apparently it's not) since there seems no default one. But then I get the further error:

```bash
{'style': PosixPath('/Users/pbb/.config/inkscape-shortcut-manager/styles'), 'object': PosixPath('/Users/pbb/.config/inkscape-shortcut-manager/objects')}
Traceback (most recent call last):
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 119, in get_socket
    s = _get_unix_socket(address)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 98, in _get_unix_socket
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 123, in get_socket
    s = _get_tcp_socket(host, dno)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 93, in _get_tcp_socket
    s.connect((host, 6000 + dno))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 107, in <module>
    main()
  File "main.py", line 79, in main
    disp = Display()
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
  File "/Users/pbb/opt/anaconda3/lib/python3.8/site-packages/Xlib/support/unix_connect.py", line 127, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":0.0": [Errno 61] Connection refused
```

I'm not sure whether it's that configuration's fault or it's the bug for this library though. Since the original repo is for Linux only, and according to the owner of that repo, he says that the only reason why this is for Linux only is that the Xlib library, hence I think this should be possible with this library.

**Comment by MestreLion** [comment]
macOS does not use `X`/`X11` at all, it uses a completely different display server called [Quartz Compositor](https://en.wikipedia.org/wiki/Quartz_Compositor), so it is expected that neither `Xlib` nor this library won't work there at all.

**Comment by vasily-v-ryabov** [comment]
At least it is a duplication of #149. There is XQuartz which should be installed additionally: https://www.xquartz.org/

**Comment by MestreLion** [comment]
@sleepymalc also note that, at least in Linux, the default `$DISPLAY` is usually `:0`, not `:0:0`,  so if you already have XQuartz you might try this.
