### ISSUE TITLE
Cannot create Display object: "AttributeError: 'Display' object has no attribute 'resource_classes'."

### ISSUE THREAD

**Issue by knuxify** [python-xlib/python-xlib#219]
I'm trying to use Xlib to move a GTK window, but when I create the Display object I get the following error:

```
Traceback (most recent call last):
  File "/tmp/aspinwall/share/aspinwall/aspinwall/shell/shellmanager.py", line 21, in on_activate
    win = Panel(app)
  File "/tmp/aspinwall/share/aspinwall/aspinwall/shell/panel.py", line 29, in __init__
    xdisplay = Display()
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/display.py", line 157, in __init__
    r = ConnectionSetupRequest(self,
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/display.py", line 1075, in __init__
    display.send_and_recv(request = -1)
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/display.py", line 612, in send_and_recv
    gotreq = self.parse_response(request)
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/display.py", line 689, in parse_response
    return self.parse_connection_setup()
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/display.py", line 958, in parse_connection_setup
    x, d = r._success_reply.parse_binary(self.data_recv[:alen],
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1203, in parse_binary
    ret[f.name], data = f.parse_binary_value(data, display,
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 533, in parse_binary_value
    ret[i], data = self.type.parse_binary(data, display)
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1192, in parse_binary
    field_val = f.parse_value(field_val, display)
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 310, in parse_value
    c = display.get_resource_class(self.class_name)
  File "/home/knuxify/.local/lib/python3.10/site-packages/Xlib/protocol/display.py", line 320, in get_resource_class
    return self.resource_classes.get(class_name, default)
AttributeError: 'Display' object has no attribute 'resource_classes'. Did you mean: 'get_resource_class'?
```

Here's the code I'm using:
```python
from Xlib.xobject.drawable import Window
from Xlib.protocol.display import Display

# ...

xwindow_id = GdkX11.X11Surface.get_xid(self.get_surface()) # self here is a Gtk.Window
xdisplay = Display() # this is where it fails
xdisplay.create_resource_object('window', xwindow_id)
xwindow.configure(x=0, y=0)
xwindow.change_attributes(
  win_gravity=X.NorthWestGravity,
  bit_gravity=X.StaticGravity
)
```

I'm using XFCE4 on Alpine Linux, xorg-server-21.1.3, Python 3.10, python-xlib 0.31.

**Comment by knuxify** [comment]
Nevermind, I was importing the wrong Display object (`from Xlib.protocol.display import Display` instead of `from Xlib.display import Display`)... :facepalm: 

Solved, closing.
