### ISSUE TITLE
"[Errno 111] Connection refused" during test run attempt in github actions

### ISSUE THREAD

**Issue by RadaevValentin** [python-xlib/python-xlib#225]
I'm trying to create github action to test lib that use python-xlib

```
 with:
    options: DISPLAY=localhost:109
    run: python -W ignore pywinauto/unittests/test_atspi_controls.py
  env:
    DISPLAY: :109
    pythonLocation: /opt/hostedtoolcache/Python/3.7.13/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.13/x64/lib
/usr/bin/sudo apt-get install -y xvfb
Reading package lists...
Building dependency tree...
Reading state information...
xvfb is already the newest version (2:1.20.13-1ubuntu1~20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
Command: python -W ignore pywinauto/unittests/test_atspi_controls.py
/usr/bin/xvfb-run --auto-servernum -s DISPLAY=localhost:109 python -W ignore pywinauto/unittests/test_atspi_controls.py
<socket.socket fd=3, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/Xlib/support/unix_connect.py", line 122, in get_socket
    s = _get_unix_socket(address)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/Xlib/support/unix_connect.py", line 100, in _get_unix_socket
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/Xlib/support/unix_connect.py", line 126, in get_socket
    s = _get_tcp_socket(host, dno)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/Xlib/support/unix_connect.py", line 94, in _get_tcp_socket
    s.connect((host, 6000 + dno))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pywinauto/unittests/test_atspi_controls.py", line 46, in <module>
    from pywinauto.linux.atspi_element_info import AtspiElementInfo
  File "./pywinauto/__init__.py", line 95, in <module>
    from . import findwindows
  File "./pywinauto/findwindows.py", line 40, in <module>
    from . import controls
  File "./pywinauto/controls/__init__.py", line 34, in <module>
    from . import atspiwrapper  # register "atspi" back-end
  File "./pywinauto/controls/atspiwrapper.py", line 39, in <module>
    from .. import backend
  File "./pywinauto/backend.py", line 35, in <module>
    from .base_wrapper import BaseWrapper
  File "./pywinauto/base_wrapper.py", line 50, in <module>
    from .mouse import _get_cursor_pos
  File "./pywinauto/mouse.py", line 50, in <module>
    _display = Display()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/Xlib/protocol/display.py", line 89, in __init__
    self.socket = connect.get_socket(name, protocol, host, displayno)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/Xlib/support/connect.py", line 87, in get_socket
    return mod.get_socket(dname, protocol, host, dno)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/Xlib/support/unix_connect.py", line 130, in get_socket
    raise error.DisplayConnectionError(dname, str(val))
Xlib.error.DisplayConnectionError: Can't connect to display ":109": [Errno 111] Connection refused
/usr/bin/bash /home/runner/work/_actions/GabrielBB/xvfb-action/v1/cleanup.sh
No xvfb processes to kill
Error: The process '/usr/bin/xvfb-run' failed with exit code 1
```

**Comment by RadaevValentin** [comment]
I also tried to run simple  script instead of tests

from Xlib.display import Display
display = Display()
root = display.screen().root

same error

**Comment by benoit-pierre** [comment]
You're starting xvfb in the background (`&`), you'll need to sleep a little to let it start properly before it's ready to accept connections.

**Comment by benoit-pierre** [comment]
Or pass the command to xvfb, which will automatically wait 3 seconds before running it so the server as time to startup.

**Comment by RadaevValentin** [comment]
My problem was solved by adding display manager into my github actions script. Thank you for your support
For me it is working this way
`
sudo apt install -y xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool
`
`
sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
`
`
sleep 5
`
`
set +eE
`
`
sudo apt install -y gdm3
`
`
sudo service gdm start
`
This issue is not relevant anymore
