### ISSUE TITLE
test fails: missing mcookie

### ISSUE THREAD

**Issue by mtelka** [python-xlib/python-xlib#257]
I tested version 0.32 and tests failed:
```
py39 run-test: commands[0] | $(BLD_DIR)/.tox/py39/bin/python -W all runtests.py
Traceback (most recent call last):
  File "$(BLD_DIR)/runtests.py", line 134, in <module>
    runtests()
  File "$(BLD_DIR)/runtests.py", line 91, in runtests
    cookie = subprocess.check_output('mcookie').strip()
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mcookie'
```

**Comment by mtelka** [comment]
The problem is that `mcookie` is typically not available on non-Linux platforms.

As a workaround one could use this script as `mcookie`:
```
#!/bin/sh

dd if=/dev/urandom of=/dev/stdout bs=512 count=1 2>/dev/null | md5sum | awk '{print $1}'
```
