### ISSUE TITLE
xfixes_get_cursor_image does not work on KDE with Xvfb exclusively

### ISSUE THREAD

**Issue by ehfd** [python-xlib/python-xlib#260]
```
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=BadAccess(<Xlib.display._BaseDisplay object at 0x7f156e2ab100>, b'\x00\n\x14\x00\r\x05\x00\x00\x04\x00\x8a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/selkies_gstreamer/__main__.py", line 719, in <lambda>
    loop.run_in_executor(None, lambda: webrtc_input.start_cursor_monitor())
  File "/usr/local/lib/python3.10/dist-packages/selkies_gstreamer/webrtc_input.py", line 441, in start_cursor_monitor
    cursor = self.xdisplay.xfixes_get_cursor_image(screen.root)
  File "/usr/local/lib/python3.10/dist-packages/Xlib/ext/xfixes.py", line 174, in get_cursor_image
    return GetCursorImage(opcode=self.display.get_extension_major(extname),
  File "/usr/local/lib/python3.10/dist-packages/Xlib/protocol/rq.py", line 1368, in __init__
    self.reply()
  File "/usr/local/lib/python3.10/dist-packages/Xlib/protocol/rq.py", line 1388, in reply
    raise self._error
Xlib.error.BadAccess: <class 'Xlib.error.BadAccess'>: code = 10, resource_id = 1293, sequence_number = 20, major_opcode = 138, minor_opcode = 4
```

This happens exclusively with KDE + Xvfb.
KDE + Xorg or Xfce4 + Xvfb works fine.
Can there be any useful inferences from the BadAccess error codes?

**Comment by ehfd** [comment]
Tagging @danisla who made the PR.

**Comment by ehfd** [comment]
Fixed by encapsulating with try: and except:...
