### ISSUE TITLE
xrandr_get_crtc_info trouble

### ISSUE THREAD

**Issue by DaWelter** [python-xlib/python-xlib#58]
I tried to use this nice library for something. Thank you for making it. However, even the xrandr example fails.
```
$git clone https://github.com/python-xlib/python-xlib.git
$cd python-xlib/examples
$python ./xrandr.py
... stuff ...
CRTC 635 info:
Traceback (most recent call last):
  File "./xrandr.py", line 196, in <module>
    Window(display.Display()).loop()
  File "./xrandr.py", line 133, in __init__
    self.pp.pprint(self.d.xrandr_get_crtc_info(crtc, resources['config_timestamp'])._data)
  File "/usr/lib/python2.7/dist-packages/Xlib/ext/randr.py", line 734, in get_crtc_info
    config_timestamp=config_timestamp,
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1478, in __init__
    self.reply()
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1490, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 729, in parse_request_response
    req._parse_response(self.data_recv[:self.request_length])
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1502, in _parse_response
    self._data, d = self._reply.parse_binary(data, self._display, rawdict = 1)
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 1325, in parse_binary
    return self.parse_binary(data, display, rawdict)
  File "<string>", line 14, in parse_binary
  File "/usr/lib/python2.7/dist-packages/Xlib/protocol/rq.py", line 510, in parse_binary_value
    v = struct.unpack(scode, data[pos: pos + slen])
struct.error: unpack requires a string argument of length 4
```
The output of the regular xrandr is
```
Screen 0: minimum 8 x 8, current 3200 x 1200, maximum 16384 x 16384
DVI-I-0 connected 1280x1024+1920+88 (normal left inverted right x axis y axis) 337mm x 270mm
   1280x1024     60.02*+  75.02  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   640x480       75.00    72.81    59.94  
DVI-I-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DVI-D-0 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 519mm x 324mm
   1920x1200     59.95*+
   1680x1050     59.95  
   1600x1200     60.00  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
DP-1 disconnected (normal left inverted right x axis y axis)
```
I have a dual monitor setup, obviously. My system is Mint Linux 18 (Ubuntu 16). Used python 2.7 for this test.

**Comment by benoit-pierre** [comment]
The backtrace shows the installed version of `python-xlib` is used, is it the same version? Does it work when run like this: `env PYTHONPATH="$PWD" python examples/xrandr.py`?

**Comment by DaWelter** [comment]
Doh! Sorry, I forgot to remove the installed version. It works now!
