### ISSUE TITLE
An exception is thrown when no .Xauthority file exists

### ISSUE THREAD

**Issue by ScoreUnder** [python-xlib/python-xlib#66]
```
Traceback (most recent call last):
  File "/home/sandbox/pxl/lib/python3.5/site-packages/Xlib/xauth.py", line 45, in __init__
    raw = open(filename, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/sandbox/.Xauthority'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sandbox/pxl/lib/python3.5/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/sandbox/pxl/lib/python3.5/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/sandbox/pxl/lib/python3.5/site-packages/Xlib/protocol/display.py", line 68, in __init__
    name, host, displayno)
  File "/home/sandbox/pxl/lib/python3.5/site-packages/Xlib/support/connect.py", line 101, in get_auth
    return mod.get_auth(sock, dname, host, dno)
  File "/home/sandbox/pxl/lib/python3.5/site-packages/Xlib/support/unix_connect.py", line 117, in new_get_auth
    au = xauth.Xauthority()
  File "/home/sandbox/pxl/lib/python3.5/site-packages/Xlib/xauth.py", line 47, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 2] No such file or directory: '/home/sandbox/.Xauthority'
```
The above exception is thrown when there is no `~/.Xauthority` file present. All non-`python-xlib` programs, such as `xrandr`, `x11vnc` and `gvim`, work fine.

**Comment by benoit-pierre** [comment]
Yeah, if `XAUTHORITY` points to a non-existent file, or `$HOME/.Xauthority` does not exist, we throw an exception, instead of just trying to connect anyway, like other clients do. Can you confirm this work with [this branch](https://github.com/python-xlib/python-xlib/compare/master...benoit-pierre:xauthority)?

**Comment by ScoreUnder** [comment]
Thanks, testing that branch it works as expected.

**Comment by benoit-pierre** [comment]
Great, thanks for testing!
