### ISSUE TITLE
Unable to call SelectInput with `SubstructureRedirectMask | SubstructureNotifyMask` mask

### ISSUE THREAD

**Issue by ekondrashev** [python-xlib/python-xlib#97]
Good day,
I was trying to port https://github.com/jichu4n/basic_wm to python using `python-xlib`, but getting failure while trying to use mask like `SubstructureRedirectMask | SubstructureNotifyMask` 

I was using `SelectInput` request class provided by `Xlib.ext.randr` package. Here is the code snippet

```
from Xlib import rdb
from Xlib.X import SubstructureRedirectMask, SubstructureNotifyMask
from Xlib.protocol.display import Display
import os

from Xlib.error import BadAccess
from Xlib.ext.randr import SelectInput


class WindowManager(object):
    def __init__(self, display):
        self.display = display
        self.root = display.screen().root
        self.other_wm_detected = False

    def on_wm_detected(self, e):
        print('On wm detected %s' % e)
        assert e.error_code == BadAccess
        self.other_wm_detected = True


    def run(self):
        self.display.set_error_handler(self.on_wm_detected)
      
        SelectInput(
            display=self.display.display,
            opcode=self.display.display.get_extension_major('RANDR'),
            window=self.root.id,
            mask=SubstructureRedirectMask | SubstructureNotifyMask
        )
        self.display.sync()
        if self.other_wm_detected:
            raise ValueError('Detected another window manager on display %s' % self.display.display)



wm_options = rdb.stdopts.copy()
wm_options['-debug'] =  rdb.SepArg('.debug')
wm_options['-version'] =  rdb.IsArg('.version')

if __name__ == "__main__":
    address = "localhost:0.0"
    os.environ[ "DISPLAY" ] = address
    extra_options = {}
    opts = wm_options.copy()
    opts.update(extra_options)

    disp, name, db, args = rdb.get_display_opts(opts)
    wm = WindowManager(disp)
    wm.run()
```

Here is the stacktrace Iḿ getting 
```
Traceback (most recent call last):
  File "/home/ekondrashev/sources/python/py-xlib/pywm.py", line 57, in <module>
    wm.run()
  File "/home/ekondrashev/sources/python/py-xlib/pywm.py", line 34, in run
    mask=SubstructureRedirectMask
  File "/home/ekondrashev/sources/python/py-xlib/venv3.5/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1350, in __init__
    self._binary = self._request.to_binary(*args, **keys)
  File "/home/ekondrashev/sources/python/py-xlib/venv3.5/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1070, in to_binary
    static_part = struct.pack(self.static_codes, *pack_items)
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)
```

**Comment by benoit-pierre** [comment]
* you're not supposed to call extension requests directly, they are automatically made available as methods to display/window; e.g.: `window.xrandr_select_input(mask)`
* `xrandr_select_input` is the equivalent of `XRRSelectInput` when using Xlib, that's not what you're looking for: the equivalent of Xlib `XSelectInput` is `window.change_attributes(event_mask=mask)`
